const IdsNC = [
    {
      id: 1,
      name: "1 - Temas Panorâmicos",
      sub: [
        { name: "Conselho de Deus" },
        { name: "Aprender Crescer e Servir" },
        { name: "Porque Jesus veio ao mundo?" },
        { name: "O Nascimento da Igreja" },
        { name: "Porta Caminho e Alvo" },
      ],
    },
    {
      id: 2,
      name: "2 - Jesus, sua vida e sua obra",
      sub: [
        { name: "Jesus é Deus" },
        { name: "Jesus é Homem" },
        { name: "A bíblia afirma: Jesus é Deus feito Homem" },
        { name: "Jesus o Messias esperado" },
        { name: "A vida de Jesus foi perfeita e irrepreensível" },
        { name: "Jesus fez uma Obra tremenda e grandiosa" },
        { name: "Jesus como nossa referência e modelo de obreiro" },
        { name: "O que Jesus ensinou?" },
        { name: "O Evangelho do Reino" },
        { name: "As 5 características de um discípulo" },
        { name: "Jesus anunciava e aplicava o Evangelho" },
        { name: "Jesus Morreu na Cruz" },
        { name: "Jesus desceu ao Hades" },
        { name: "Jesus Ressuscitou - Parte 1" },
        { name: "Jesus Ressuscitou - Parte 2" },
        { name: "Jesus foi exaltado à destra do Pai" },
        { name: "Jesus após a exaltação" },
        { name: "O que Jesus ensinou sobre a Sua volta" },
      ],
    },
    {
      id: 3,
      name: "4 - Jesus é a porta do Reino",
      sub: [
        { name: "A fé que salva - Parte 1" },
        { name: "A fé que salva - Parte 2" },
        { name: "Arrependimento - Parte 1" },
        { name: "Arrependimento - Parte 2" },
        { name: "Batismo em Cristo" },
        { name: "Batismo com Espírito Santo" },
        {
          name: "A habitação do Espírito Santo e o batismo com o Espírito Santo",
        },
        { name: "Recebereis poder" },
      ],
    },
    {
      id: 4,
      name: "5 - O Espírito Santo",
      sub: [
        { name: "O Espírito Santo é Deus" },
        { name: "O Espírito Santo na história" },
        { name: "O Espírito Santo e os apóstolos" },
        { name: "O Espírito Santo e a Igreja" },
        { name: "O Espírito e a noiva dizem: Vem!" },
        { name: "O Espírito Santo e a Bíblia" },
        { name: "O caráter do Espírito Santo" },
        { name: "Andando no Espírito" },
        { name: "Os dons do Espírito Santo" },
      ],
    },
    {
      id: 5,
      name: "8 - Os primeiros passos no Caminho",
      sub: [
        { name: "Perdoar - Parte 1" },
        { name: "Perdoar - Parte 2" },
        { name: "Confessar pecados" },
        { name: "Ser transparente" },
        { name: "Perseverar na Palavra" },
        { name: "Perseverar na oração" },
        { name: "Perseverar no Jejum" },
        { name: "Perseverar no partir do pão" },
        { name: "Perseverar na comunhão" },
        { name: "Proclamar o Evangelho" },
      ],
    },
    {
      id: 6,
      name: "9 - Caminhando como Sacerdote",
      sub: [
        { name: "Proclamar o Evangelho" },
        { name: "O sacerdócio de todos os santos" },
        { name: "Os ministérios" },
        { name: "A Igreja na casa - Parte 1" },
        { name: "A Igreja na casa - Parte 2" },
        { name: "O que são juntas e ligamentos" },
        { name: "Juntas e ligamentos: Discipulado - Parte 1" },
        { name: "Juntas e ligamentos: Discipulado - Parte 2" },
        { name: "Juntas e ligamentos: Companheirismo - Parte 1" },
        { name: "Juntas e ligamentos: Companheirismo - Parte 2" },
        { name: "Juntas e ligamentos naturais: Família" },
      ],
    },
    {
      id: 7,
      name: "6 - O Deus pai",
      sub: [
        { name: "O Deus triuno" },
        { name: "Mostra-nos o Pai" },
        { name: "Quem é o Pai?" },
        { name: "O Pai o amará" },
        { name: "Uma família para o Pai" },
        { name: "Uma noiva para o Filho" },
        { name: "Um edifício para o Espírito Santo" },
      ],
    },
    {
      id: 8,
      name: "3 - A volta de Jesus",
      sub: [
        { name: "Porque e como estudar sobre a volta de Jesus" },
        { name: "As 70 semanas de Daniel" },
        { name: "A volta de Jesus: O ensino apostólico - Parte 1" },
        { name: "A volta de Jesus: O ensino apostólico - Parte 2" },
        { name: "A volta de Jesus: O ensino apostólico - Parte 3" },
        { name: "O Jesus que virá" },
        { name: "Arrebatamento secreto?" },
        { name: "Apocalipse - Parte 1: As cartas às sete igrejas" },
        { name: "Apocalipse - Parte 2: O Cordeiro" },
        { name: "Apocalipse - Parte 3: Os acontecimentos finais" },
        { name: "Apocalipse - Parte 4: O milênio" },
        { name: "Jesus volta para os fiéis e prudentes" },
      ],
    },
    {
      id: 9,
      name: "9 - Parte 2 - Caminhando como Sacerdote",
      sub: [
        { name: "Discipulado e autoritarismo" },
        { name: "O valor da sujeição" },
        { name: "Catequese" },
        { name: "Cooperadores" },
        { name: "Capacitando os discipuladores" },
      ],
    },
  ];

  export default IdsNC

